### ISSUE TITLE
하나의 인스턴스에서 운영 서버와 개발 서버를 동시에 무중단 배포 하도록 구현

### ISSUE THREAD

**Issue by Mingyum-Kim** [dnd-side-project/dnd-9th-1-backend#101]
### 1️⃣ 설명 (Description)

하나의 EC2 인스턴스에서 두 개의 브랜치 (main, dev) 로 각각 운영 서버와 개발 서버로 운영하고자 한다. 
동시에 무중단 배포를 해야하기 때문에 총 4 개의 스프링 부트를 실행해야 하고, 이에 따라 프리티어의 한도 내에서 볼륨을 30 GB로 조정한다.
dev 서버에서 테스트 후 문제가 없다면 prod 서버로 이전하여 dev 서버를 추가로 설치하고, dev 서버는 종료한다. (요금 과금 문제) 

### 2️⃣ To-do
- [x] 무중단 배포 로직을 두 개로 분리하기
- [x] dev 브랜치에 대한 8083, 8084 포트의 무중단 배포 동작 확인
- [x] prod 브랜치에 대한 8081, 8082 포트의 무중단 배포 동작 확인
- [x] 서브 도메인 접속 후 스웨거 테스트
- [x] 서브 도메인에 대한 SSL 인증서 발급 및 등록
