### ISSUE TITLE
LoginRequest의 파라미터를 userId로 변경해서 구현

### ISSUE THREAD

**Issue by Mingyum-Kim** [dnd-side-project/dnd-9th-1-backend#11]
### 1️⃣ 설명 (Description)

기존 로그인 Controller에서 access token과 provider를 입력받아 구현했던 것을, userId를 받는 것으로 변경하여 구현한다. 이 때 userId는 사용자 PK가 아니라 카카오, 애플 서버에서 제공하는 social Id이다.

### 2️⃣ To-do

- [x] AuthController 파라미터 변경
- [x] AuthService를 userId를 통해 회원 유무를 검증하고 회원가입 or 로그인 처리하는 것으로 변경
- [x] nickname 필드 전부 제외
