### ISSUE TITLE
상위 목표 달성 시 보상을 제공하는 기능과 팝업 구현

### ISSUE THREAD

**Issue by jemlog** [dnd-side-project/dnd-9th-1-backend#23]
### 1️⃣ 설명 (Description)
상위 목표 달성 시 20개의 보석 중 랜덤으로 하나를 보상으로 제공하는 기능을 제공합니다. 
### 2️⃣ To-do

- [x] 상위 목표 달성 시 보석 지급 기능 구현
- [x] 상위 목표 달성 시 complete 상태의 상위 목표 개수 조회 기능 구현
- [x] 완료함 리스트 조회 시 획득한 보석 이미지 함께 보여주는 기능 추가
