### ISSUE TITLE
dev 환경에서 데이터베이스 환경 구축

### ISSUE THREAD

**Issue by Mingyum-Kim** [dnd-side-project/dnd-9th-1-backend#7]
### 1️⃣ 설명 (Description)

현재 github 상에 application.yml이 존재하지 않아 DB가 연결되어있지 않다. 따라서 github actions에서 gradlew build와 test 시 에러가 발생하고 있는데, git submodules를 활용해서 문제를 해결하려 한다.
RDS는 프리티어가 내 계정에는 적용되지 않아 우선 서버 내에 MariaDB를 설치하여 dev 환경에서와 연결한다.

### 2️⃣ To-do

- [x] 서버 내 Database 설치
- [x] Submodule 설정
- [x] local, dev 환경 분리해서 application.yml 파일 생성
- [x] build.yml 파일 수정
